version: '3.8'

services:
  db:
    image: postgres:15
    container_name: afiliadosbet-db
    restart: always
    environment:
      POSTGRES_DB: afiliadosbet
      POSTGRES_USER: afiliados
      POSTGRES_PASSWORD: supersecret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: afiliadosbet-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: afiliadosbet-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
